import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";

const poppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppinsFont",
});

export const metadata: Metadata = {
  title: "Rental Mobil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppinsFont.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
